version: '3'

services:

  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    ports:
      - "3000:8080"
    environment: 
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=${ENV}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - WEBUI_NAME=${WEBUI_NAME}
    volumes:
      - globaldatabank_webui_local:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure:5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - globaldatabank_ollama_local:/root/.ollama
    tty: true
    restart: on-failure:5

